### ISSUE TITLE
tasks to be done

### ISSUE THREAD

**Issue by rchtgpt** [sync-x/spot#1]
- [x] Log in page #2 
- [x] Sign up page #2 
- [x] Menu
* Classify (Plants and Diseases)
* Weather Conditions (location picker)
* Nearby Nursery (Map Integration)
* Profile

Created `BottomNavigationView` for menu
- [ ] TFlite model inside Classifier #3 
- [ ] TFlite UI #3 
- [ ] Profile Activity (Data History)

**Comment by oorjitchowdhary** [comment]
Creating issues for each of the feature for modularity.
